FROM ubuntu:latest as base
WORKDIR /app

RUN apt-get update && \
    apt-get install -y openjdk-17-jdk-headless gradle && \
    apt-get clean

FROM base as dependencies
COPY gradlew .
COPY gradle/ gradle/
COPY build.gradle .
COPY settings.gradle .

RUN chmod +x ./gradlew
RUN ./gradlew --no-daemon dependencies

FROM dependencies as builder
COPY src src

RUN ./gradlew --no-daemon build

FROM openjdk:17
WORKDIR /app

ARG SPRING_DATA_MONGODB_URI
ARG SPRING_DATA_MONGODB_DATABASE
ARG SPRING_SECURITY_AUTH_LIVEBLOCKSECRETKEY
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG GOOGLE_REDIRECT_URI
ARG GOOGLE_TOKEN_URI
ARG GOOGLE_USER_INFO_URI
ARG JWT_SECRET
ARG JWT_EXPIRATION
ARG CORS_ALLOWED_ORIGINS
ARG CORS_ALLOWED_METHODS
ARG CORS_ALLOWED_HEADERS

ENV SPRING_DATA_MONGODB_URI=$SPRING_DATA_MONGODB_URI
ENV SPRING_DATA_MONGODB_DATABASE=$SPRING_DATA_MONGODB_DATABASE
ENV SPRING_SECURITY_AUTH_LIVEBLOCKSECRETKEY=$SPRING_SECURITY_AUTH_LIVEBLOCKSECRETKEY
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV GOOGLE_REDIRECT_URI=$GOOGLE_REDIRECT_URI
ENV GOOGLE_TOKEN_URI=$GOOGLE_TOKEN_URI
ENV GOOGLE_USER_INFO_URI=$GOOGLE_USER_INFO_URI
ENV JWT_SECRET=$JWT_SECRET
ENV JWT_EXPIRATION=$JWT_EXPIRATION
ENV CORS_ALLOWED_ORIGINS=$CORS_ALLOWED_ORIGINS
ENV CORS_ALLOWED_METHODS=$CORS_ALLOWED_METHODS
ENV CORS_ALLOWED_HEADERS=$CORS_ALLOWED_HEADERS

# Copy the built jar file
COPY --from=builder /app/build/libs/*.jar app.jar

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
